source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "audited", "~> 4.6"
gem 'bcrypt', '~> 3.1', '>= 3.1.11'
gem 'bugsnag'
gem 'bootstrap-sass', '~> 3.3.7'
gem "breadcrumbs_on_rails"
gem 'bootstrap-daterangepicker-rails'
gem 'coffee-rails', '~> 4.2'
gem 'daemons'
gem 'delayed_job_active_record'
# gem 'font-awesome-rails'
gem 'font_awesome5_rails'
gem 'jbuilder', '~> 2.5'
gem 'jquery-datatables-rails', '~> 3.4.0'
gem 'jquery-rails', '~> 4.3.1'
gem 'jquery-turbolinks'
gem 'kaminari', '~> 1.0.1'
gem 'minidusen'
gem 'momentjs-rails'
gem 'mysql2', '>= 0.3.18', '< 0.5'
gem 'puma', '~> 3.7'
gem 'rails', '~> 5.1.4'
gem 'rails-erd', require: false, group: :development
gem 'redis-rails'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
gem 'useragent'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'

  gem 'capistrano'
  gem 'capistrano-bundler'
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'capistrano-rbenv'
  gem 'capistrano3-delayed-job'
end

group :production do
  gem 'mini_racer'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
